version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPW
      POSTGRES_DB: nestjs
    networks:
      - vodonesia
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "5100:5100"
    volumes:
      - npm-cache:/root/.npm
networks:
  vodonesia:
volumes:
  npm-cache:
    external: false
